# Generated by Django 4.2.3 on 2023-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appuser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uname', models.CharField(max_length=25)),
                ('phno', models.BigIntegerField()),
                ('mailid', models.CharField(max_length=50)),
                ('doorno', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pas', models.CharField(max_length=512)),
                ('coin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('caid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sub1', models.CharField(max_length=25)),
                ('sub2', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vname', models.CharField(max_length=30)),
                ('phno', models.BigIntegerField()),
                ('street', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pas', models.CharField(max_length=512)),
            ],
        ),
    ]
