# Generated by Django 4.2.3 on 2023-08-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='images')),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phno', models.BigIntegerField()),
                ('mailid', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pas', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='mailid',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='mailid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='uname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vname',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='viewlist',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='caid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.vendor'),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('typ', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
                ('state', models.BooleanField()),
                ('uid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
                ('vid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('text', models.CharField(max_length=100)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.staff')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='alert',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.appuser')),
            ],
        ),
    ]
