# Generated by Django 4.2.3 on 2023-10-15 11:34

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_product_staff_vendor_mailid_alter_appuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.upload_to),
        ),
    ]
