# Generated by Django 4.2.3 on 2023-10-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_product_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic',
        ),
    ]
